OM-3006: changing default for pagination
OnCorps/doctrine2-exporter pull request #18
Opened 2019-12-10 17:05 UTC by domgraziano

and adding mechanism to add more attributes to api plarform in classes.

2019-12-10 17:30 UTC, nigel-dunn requested changes

2019-12-10 17:30 UTC, nigel-dunn commented on README_ApiPlatform.md
> +    enabled: [true | false] - If option is fully omitted then default would be hinerited by global configuration in api-platform.yaml
```suggestion
    enabled: [true | false] - If not specified then the default is to inherit the global setting in api-platform.yaml
```

2019-12-10 17:30 UTC, nigel-dunn commented on lib/MwbExporter/Formatter/Doctrine2/Annotation/ApiPlatform/Attributes/ClassLevelAttributeAnnotations.php
> +    protected $attributes = [];
Can these be `private` please.

2019-12-10 17:30 UTC, nigel-dunn commented on lib/MwbExporter/Formatter/Doctrine2/Annotation/ApiPlatform/Attributes/ClassLevelAttributeAnnotations.php
> +    private function buildAnnotations()
```suggestion
    private function buildAnnotations(): void
```

2019-12-10 17:30 UTC, nigel-dunn commented on lib/MwbExporter/Formatter/Doctrine2/Annotation/ApiPlatform/Attributes/CommentSettingGenerator.php
> +    public function getKeyValueSettingsFromComment(?string $comment = '')
```suggestion
    public function getKeyValueSettingsFromComment(?string $comment = ''): array
```

2019-12-10 17:30 UTC, nigel-dunn commented on lib/MwbExporter/Formatter/Doctrine2/Annotation/ApiPlatform/Attributes/PaginationAttributeBuilder.php
> +    private $table;
```suggestion
    /**
     * @var Table
     */
    private $table;
```

2019-12-10 17:30 UTC, nigel-dunn commented on lib/MwbExporter/Formatter/Doctrine2/Annotation/ApiPlatform/Attributes/PaginationAttributeBuilder.php
> +    private $commentSettingGenerator;
```suggestion
    /**
     * @var CommentSettingGenerator
     */
    private $commentSettingGenerator;
```

2019-12-10 17:30 UTC, nigel-dunn commented on lib/MwbExporter/Formatter/Doctrine2/Annotation/ApiPlatform/Attributes/PaginationAttributeBuilder.php
> +    public function buildAttribute(): ?string
```suggestion
    /**
     * @inheritdoc
     */
    public function buildAttribute(): ?string
```

2019-12-11 10:15 UTC, markbirch101 approved these changes
Changes 'enabling pagination' behaviour so that If not specified then the default is to inherit the global setting in api-platform.yaml

2019-12-11 10:23 UTC, nigel-dunn approved these changes

2019-12-11 10:23 UTC, merged